grandinetech/rust-kzg

Arkworks/src/kzg_proofs.rs
Arkworks/src/kzg_types.rs
ckzg/src/kzgsettings.rs
kzg-bench/src/tests/kzg_proofs.rs
kzg/src/lib.rs

because c-kzg passes it as const pointer to FFTSettings:
```c
C_KZG_RET new_kzg_settings(KZGSettings *ks, const g1_t *secret_g1, const g2_t *secret_g2, uint64_t length,
const FFTSettings *fs);
```
which implies that the same FFTSettings instance can be reused for different KZGSettings' instances, which at the present moment wasn't possible due to the move being invoked on FFTSettings

Pass FFTSettings as reference

---

ckzg/Cargo.toml
ckzg/benches/kzg.rs
kzg-bench/src/benches/kzg.rs
kzg-bench/src/benches/mod.rs

Because:
* it wasn't included in `mod.rs`
* `destroy` methods were made obsolete in #77
* wrong iteration
* wrong `id` string

Fix kzg bench

---

.github/workflows/ci.yml
mcl-kzg/kzg-bench/src/test.rs
mcl-kzg/kzg-bench/src/test_macro.rs
mcl-kzg/kzg/Cargo.toml
mcl-kzg/kzg/src/data_recovery.rs
mcl-kzg/kzg/src/data_types/fp.rs
mcl-kzg/kzg/src/data_types/fp2.rs
mcl-kzg/kzg/src/data_types/fr.rs
mcl-kzg/kzg/src/data_types/g1.rs
mcl-kzg/kzg/src/data_types/g2.rs
mcl-kzg/kzg/src/data_types/gt.rs
mcl-kzg/kzg/src/init_def.rs
mcl-kzg/kzg/src/mcl_methods.rs

This branch is just a reset of original `mcl/style-fixes` branch, back to the changes before "new" `MaybeUninit` implementation.
It contains:
- MaybeUninit changed to simply `type::zero()`,
- Using `OnceCell` instead of `static mut` variables in Recovery.

[Mcl]Style fixes alternative

---

mcl/kzg-bench/Cargo.toml
mcl/kzg-bench/benches/shared_eip_4844.rs
mcl/kzg/src/eip_4844.rs

Benchmarks completed locally, although slower that blst.

mcl: add benches for eip_4844

---

blst-from-scratch/benches/eip_4844.rs
blst-from-scratch/src/eip_4844.rs
blst-from-scratch/tests/eip_4844.rs
kzg-bench/src/benches/eip_4844.rs
kzg-bench/src/tests/eip_4844.rs
kzg-bench/src/tests/fk20_proofs.rs

Ported c-kzg [tests found in nodejs bindings](https://github.com/ethereum/c-kzg-4844/blob/1d3282895dae3dffc7fb0c65877fb039b5541ee0/bindings/node.js/test.ts) that deal with edge cases (mainly n < 2 in aggregate functions). 
Test verify_aggregate_kzg_proof_test_empty is commented out as it currently is [skipped in the nodejs bindings](https://github.com/ethereum/c-kzg-4844/blob/1d3282895dae3dffc7fb0c65877fb039b5541ee0/bindings/node.js/test.ts#L54).
Added benchmarks with varying numbers (4, 8, and 16) of blobs for compute_aggregate_kzg_proof.

Add more tests and benchmarks for the new interface

---

.github/workflows/ci.yml
Cargo.lock
blst-from-scratch/Cargo.toml
blst-from-scratch/src/data_availability_sampling.rs
blst-from-scratch/src/eip_4844.rs
blst-from-scratch/src/fft_fr.rs
blst-from-scratch/src/fft_g1.rs
blst-from-scratch/src/fk20_proofs.rs
blst-from-scratch/src/kzg_proofs.rs
blst-from-scratch/src/lib.rs
blst-from-scratch/src/recovery.rs
blst-from-scratch/src/types/fft_settings.rs
blst-from-scratch/src/types/fk20_multi_settings.rs
blst-from-scratch/src/types/fk20_single_settings.rs
blst-from-scratch/src/types/fr.rs
blst-from-scratch/src/types/g1.rs
blst-from-scratch/src/types/g2.rs
blst-from-scratch/src/types/kzg_settings.rs
blst-from-scratch/src/types/poly.rs
blst-from-scratch/src/utils.rs
blst-from-scratch/src/zero_poly.rs
kzg/Cargo.toml
kzg/src/lib.rs
rust-toolchain.toml

Initially my goal was to make it `no_std` compatible and it almost is, but `blst` isn't (see https://github.com/supranational/blst/pull/150), without that it still compiles for `wasm32-unknown-unknown` target, but wouldn't work for target that doesn't have standard library at all.
I'll send a PR with full `no_std` support once https://github.com/supranational/blst/pull/150 or similar is upstreamed.
Wasm is skipped in CI on macOS because it needs proper Clang with wasm support and not the default Apple's contraption. But it didn't seem worthwhile to add LLVM installation on top since if it works on Linux and Windows, it'll work the same exact way on macOS too given compiler support.

Wasm support

---

Arkworks/src/kzg_types.rs
blst-from-scratch/src/types/g1.rs
blst-from-scratch/src/types/g2.rs
ckzg/src/fftsettings.rs
ckzg/src/finite.rs
ckzg/src/fk20settings.rs
ckzg/src/kzgsettings.rs
ckzg/src/kzgsettings4844.rs
kzg/src/lib.rs
mcl/kzg/src/trait_implementations/g1.rs
mcl/kzg/src/trait_implementations/g2.rs
zkcrypto/src/eip_4844.rs
zkcrypto/src/fft_g1.rs
zkcrypto/src/kzg_types.rs

Wanted to derive `Default` on `FsG1` and noticed that I forgot one more place with `Default` during earlier refactoring

Make `G1` and `G2` traits depend on `Default` rather than having own `default` method

---

blst-from-scratch/Cargo.toml
kzg/Cargo.toml
kzg/src/lib.rs

When I tried to use `blst_from_scratch` in `no_std` environment, turned out that `kzg` crate needs to be adapted a bit too.

`no_std` support in `kzg` crate

---

blst-from-scratch/src/kzg_proofs.rs
blst-from-scratch/src/types/g2.rs
blst-from-scratch/tests/kzg_proofs.rs

- Add `rand()` method to FsG2
- Add test for `pairings_verify` that checks `blst::Pairing semantics`
- Replace pairing computation with more efficient implementation in kzg_proofs.rs
BLST offers an efficient `Pairing` engine which mutualizes the miller loop computation.
The API for this binding, `blst_miller_loop_n` is alas not public, but there is a public `Pairing` engine built for BLS12-381 signatures that is available and maps to this API. All it requires is passing a dst, for which a dummy parameter is chosen.
Result on my machine (using the eip_4844 benchmark):
```
verify_kzg_proof        time:   [809.05 µs 815.95 µs 826.04 µs]
change: [-13.766% -9.1251% -6.1879%] (p = 0.00 < 0.05)
Performance has improved.
Found 5 outliers among 100 measurements (5.00%)
2 (2.00%) high mild
3 …
```

refactor: Optimize pairing computation in blst_from_scratch/pairing_verify.

---

.github/workflows/blst-benchmarks.yml
.github/workflows/blst-tests.yml
.github/workflows/mcl-benchmarks.yml
.github/workflows/mcl-tests.yml
blst-from-scratch/go.patch
blst-from-scratch/nodejs.patch
blst-from-scratch/run-c-kzg-4844-tests.sh
blst-from-scratch/rust.patch
mcl/kzg/go.patch
mcl/kzg/nodejs.patch
mcl/kzg/run-c-kzg-4844-tests.sh
mcl/kzg/rust.patch

Updated `c-kzg-4844` git hash to [fd24cf8](https://github.com/ethereum/c-kzg-4844/tree/fd24cf8e1e2f09a96b4e62a595b4e49f046ce6cf)

Update git hash

---

blst-from-scratch/src/eip_4844.rs
blst-from-scratch/src/fk20_proofs.rs
blst-from-scratch/src/recovery.rs
blst-from-scratch/src/types/fk20_multi_settings.rs
blst-from-scratch/src/types/fk20_single_settings.rs
blst-from-scratch/src/types/g2.rs
blst-from-scratch/src/types/kzg_settings.rs
blst-from-scratch/src/types/poly.rs
blst-from-scratch/src/utils.rs
blst-from-scratch/src/zero_poly.rs
kzg-bench/src/benches/recover.rs

I was looking at recovery code trying to find a way to optimize it. In the end I went through a large chunk of the code, replacing manual indexing of vectors with idiomatic iterators and pre-allocating vectors with known size to avoid re-allocations.
End result isn't impressive, from my testing improvement is 1-5%, benchmark is very noisy, I blame it on heterogeneous cores of my 13900K processor. But it is faster in general.
One question I have is whether `recover_poly_from_samples` should be removed from `recovery.rs` and its changes moved into `FsPoly::recover_poly_from_samples` (there is some extra parallelization there for instance, but for the most part functions are just duplicates of each other).

Idiomatic Rust refactoring

---

blst-from-scratch/Cargo.toml
kzg/Cargo.toml

Regressed with recent changes, the most annoying thing with `wasm32-unknown-unknown` is that it does have `std`, it is just incomplete

Fix `no_std` support

---

Arkworks/Cargo.toml
Arkworks/benches/kzg.rs
Arkworks/benches/lincomb.rs
Arkworks/src/fft_g1.rs
blst-from-scratch/Cargo.toml
blst-from-scratch/benches/kzg.rs
blst-from-scratch/benches/lincomb.rs
ckzg/benches/kzg.rs
kzg-bench/src/benches/kzg.rs
kzg-bench/src/benches/lincomb.rs
kzg-bench/src/benches/mod.rs
mcl/kzg-bench/Cargo.toml
mcl/kzg-bench/benches/shared_kzg_proof.rs
mcl/kzg-bench/benches/shared_lincomb.rs
mcl/kzg/src/data_types/g1.rs
zkcrypto/Cargo.toml
zkcrypto/benches/kzg.rs
zkcrypto/benches/lincomb.rs

- New benchmarks: `compute_proof_single` and `g1_lincomb`
- Arkworks: use parallel iterators in G1 linear combination
- Mcl: naive parallel approach for G1 linear combination

New benchmarks and improved G1 linear combination

---

Arkworks/src/zero_poly.rs
Cargo.lock
blst-from-scratch/Cargo.toml
blst-from-scratch/src/fft_fr.rs
blst-from-scratch/src/types/poly.rs
blst-from-scratch/src/zero_poly.rs
kzg/src/lib.rs
mcl/kzg/src/zero_poly.rs
zkcrypto/src/zero_poly.rs

I was trying to get substantial improvements given how inefficient it seems (over 50% of cache misses, CPU cores underutilized in parallel mode, etc).
The changes I did are mechanical, they don't change what code does, only (a bit) how. I think there is still improvements to be done in `zero_poly_via_multiplication`, but I don't have enough math background for now, maybe we'll tackle it with @dariolina in the future. I have not checked assembly, but I think Rust is not able to statically verify bounds in all cases and that might result in extra checks still present in the binary that could be eliminated with better structured code or some unsafe operations.
Net result is ~2x performance improvement for recover benchmark with scale 15 in parallel mode. If we can bump `DEGREE_OF_PARTIAL` …

Improve recovery performance

---

arkworks/src/recover.rs
blst/src/recovery.rs
blst/src/types/poly.rs
kzg/src/lib.rs
mcl/kzg/src/data_recovery.rs
mcl/kzg/src/trait_implementations/poly.rs
zkcrypto/src/recover.rs

First commit just moves trait implementation from one file to another, as discussed previously the standalone function is not necessary. Second commit adds new method to all implementations in a straightforward way (except `ckzg` that does not compile anyway).
Resolves #200

Recover poly coefficients

---

blst/src/eip_4844.rs
kzg/src/eip_4844.rs
mcl/kzg/src/c_bindings.rs

Bindings that used the exported function `verify_blob_kzg_proof_batch` were 2x slower than the native implementation because rust-kzg with blst backend in `FsG1::from_bytes` performs additional checks (according to the spec), such as:
* whether the point is on the curve
* whether the point is on the right subgroup
Here are the local benchmark results for hooking up the blst backend to the Rust binding from c-kzg-4844. I ran it twice, first without my changes and then with my changes:
<details><summary>Details</summary>
<p>
```text
verify_blob_kzg_proof_batch/1
time:   [3.2226 ms 3.2301 ms 3.2381 ms]
thrpt:  [308.83  elem/s 309.59  elem/s 310.31  elem/s]
change:
time:   [-0.4537% -0.0829% +0.2789%] (p = 0.66 > 0.05)
thrpt:  [-0.2781% +0.0830% +0.4558%]
No change in performance detected. …
```

Fix slow type conversion in C API

---

.github/workflows/release.yml
blst/Cargo.toml

First commit removes features of `blst` that shouldn't be necessary (and shouldn't exist in `blst` in the first place) as described in https://github.com/sifraitech/rust-kzg/pull/233#discussion_r1336346607.
Second commit fixes regression from https://github.com/sifraitech/rust-kzg/pull/232 that caused `hex` dependency to pull standard library in (annoyingly `wasm32-unknown-unknown` does have a standard library, although an incomplete one, so it didn't cause CI failure).

Fix features

---

arkworks/src/kzg_types.rs
blst/src/types/g1.rs
constantine/src/types/g1.rs
kzg-bench/src/tests/msm/batch_adder.rs
kzg/src/lib.rs
kzg/src/msm/arkmsm/bucket_msm.rs
zkcrypto/benches/eip_4844.rs
zkcrypto/benches/fk_20.rs
zkcrypto/benches/kzg.rs
zkcrypto/benches/lincomb.rs
zkcrypto/bls12_381/src/g1.rs
zkcrypto/bls12_381/src/lib.rs
zkcrypto/src/eip_4844.rs
zkcrypto/src/fft_g1.rs
zkcrypto/src/fk20_proofs.rs
zkcrypto/src/kzg_proofs.rs
zkcrypto/src/kzg_types.rs
zkcrypto/tests/bls12_381.rs
zkcrypto/tests/eip_4844.rs
zkcrypto/tests/fk20_proofs.rs
zkcrypto/tests/kzg_proofs.rs

implements missing traits so that zkcrypto backend compiles
not compatible with kzg generic msm

zkcrypto - impl missing traits

---

.github/workflows/release.yml

Was copy-pasting from different workflow file & forgot that we don't use 'os' matrix (releases are all built on ubuntu-latest image)

fix constantine dep install on release

---

Cargo.lock
arkworks/Cargo.toml
arkworks/src/eip_4844.rs
arkworks/src/kzg_proofs.rs
arkworks/src/kzg_types.rs
blst/Cargo.toml
blst/src/eip_4844.rs
constantine/Cargo.toml
constantine/src/eip_4844.rs
constantine/src/types/kzg_settings.rs
kzg/Cargo.toml
kzg/src/eip_4844.rs
kzg/src/msm/bgmw.rs

In this PR:
* `bgmw` feature enabled for blst, arkworks, and constantine backends.
* Picked better window size for `BGMW` when point count = `4096` (trusted setup size)

Enable BGMW by default

---

.github/workflows/backend-benchmarks.yml
.github/workflows/backend-tests.yml
.github/workflows/release.yml
arkworks/nim.patch
arkworks/rust.patch
blst/nim.patch
blst/rust.patch
constantine/nim.patch
constantine/rust.patch
run-c-kzg-4844-tests.sh
zkcrypto/nim.patch
zkcrypto/rust.patch

In this PR:
* Update `C_KZG_4844_GIT_HASH` to latest c-kzg-4844 commit ([`5115420`](https://github.com/ethereum/c-kzg-4844/tree/5115420ba3f919f5501155ba18633667001b6a07))
* Added support for nim bindings

Bump C_KZG_4844_GIT_HASH

---

blst/src/types/fr.rs
blst/src/types/g2.rs

Other types had `#[repr(C)]` on them already. This is important for FFI purposes.

Add `#[repr(C)]` on a few remaining `blst` types

---

arkworks/Cargo.toml
arkworks/src/eip_4844.rs
arkworks/src/eip_7594.rs
arkworks/src/utils.rs
arkworks3/Cargo.toml
arkworks3/src/eip_4844.rs
arkworks3/src/eip_7594.rs
arkworks3/src/utils.rs
blst/Cargo.toml
blst/src/eip_4844.rs
blst/src/eip_7594.rs
blst/src/utils.rs
blst/tests/c_bindings.rs
constantine/Cargo.toml
constantine/src/eip_4844.rs
constantine/src/eip_7594.rs
constantine/src/utils.rs
constantine/tests/c_bindings.rs
kzg/src/eip_4844.rs
readme.md
run-c-kzg-4844-benches.sh
run-c-kzg-4844-fuzz.sh
run-c-kzg-4844-tests.sh
zkcrypto/Cargo.toml
zkcrypto/src/eip_4844.rs
zkcrypto/src/eip_7594.rs
zkcrypto/src/utils.rs

In this PR:
* Added "c_bindings" feature in backend crates, allowing to optionally disable C bindings
* Added `_raw` functions, that accept raw bytes
Related: https://github.com/grandinetech/grandine/issues/73

Optionally disable c bindings

---

.github/workflows/backend-tests.yml
arkworks/Cargo.toml
arkworks/benches/eip_7594.rs
arkworks3/Cargo.toml
arkworks3/benches/eip_7594.rs
zkcrypto/Cargo.toml
zkcrypto/benches/eip_7594.rs

In this PR:
* Added EIP-7594 benchmarks for `arkworks`, `arkworks3` & `zkcrypto` backends
* Enabled `c_bindings` feature, when running tests in CI - in #278 we've decided to disable this feature by default, but some tests depend on it and I forgot to enable it back :)

Enable peer das benchmarks for arkworks, arkworks3 and zkcrypto backends

---

kzg/src/common_utils.rs
kzg/src/das.rs
kzg/src/eth/eip_7594.rs
kzg/src/eth/mod.rs

This pull request will add raw functions into DAS trait, like eip4844 in this [commit](https://github.com/grandinetech/rust-kzg/commit/6d33a883a1c552e1e10ca4e56249a18f4c8fed90#diff-70df151cb548dfa1811d5c198927567fb09e94e7b7b0c11a3326a0a9fcaf9570). The idea is to allow easier integration into its domain without needing to transform unit type into underlying field element type (e.g. converting [`Cell`](https://github.com/ethereum/consensus-specs/blob/b1c70a96883feddb194eba4f3a033a8b53f0d082/specs/fulu/polynomial-commitments-sampling.md?plain=1#L74) into field elements), which adding more complexity into the integration. The WIP integration into `grandine` can be found [here](https://github.com/hangleang/grandine/tree/rust-kzg-integration).
NOTE: the current changes has a few bugs (potential …

PeerDAS: Add raw functions like eip4844

---

.github/workflows/release.yml

actions/upload-artifact@v3 and actions/download-artifact@v3 [are deprecated](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/), and currently fail on main branch.
This PR updates them to `v4`.

Fixed automatic release action

---

Cargo.lock
arkworks3-sppark/Cargo.toml
arkworks3-sppark/cuda/pippenger.cu
blst-sppark/Cargo.toml
blst-sppark/cuda/pippenger.cu

This PR:
* Updates sppark to latest version `0.1.11`.
Needed for GPU-accelerated backend integration in https://github.com/grandinetech/grandine/pull/88

Updated sppark to 0.1.11

---

Cargo.lock
arkworks3/src/kzg_types.rs
arkworks4/src/kzg_types.rs
arkworks5/src/kzg_types.rs
blst/src/types/g1.rs
blst/src/types/kzg_settings.rs
constantine/src/mixed_kzg/mixed_kzg_settings.rs
constantine/src/types/g1.rs
constantine/src/types/kzg_settings.rs
kzg-bench/src/benches/eip_7594.rs
kzg-bench/src/benches/lincomb.rs
kzg-bench/src/tests/bls12_381.rs
kzg/Cargo.toml
kzg/src/das.rs
kzg/src/lib.rs
kzg/src/msm/bgmw.rs
kzg/src/msm/precompute.rs
kzg/src/msm/sppark.rs
mcl/src/types/g1.rs
mcl/src/types/kzg_settings.rs
run-c-kzg-4844-benches.sh
zkcrypto/src/kzg_types.rs

In this PR, several optimizations are ported from [`rust-eth-kzg`](https://github.com/crate-crypto/rust-eth-kzg):
1. Batch multiplication precomputation - doing precomputations after loading trusted setup
2. Using HashMap for deduplicate_commitments
3. Using HashSet to find missing cell indices in cell recovery
4. Batch inverse
Parallel benchmark times, with avg. CPU load:
|                                              |  rust-kzg | avg load |
| -------------------------------------------- | --------: | -------: |
| compute_cells_and_kzg_proofs                 | 48.513 ms |  27%-30% |
| recover_cells_and_kzg_proofs (50% missing)   | 59.624 ms |   25-30% |
| recover_cells_and_kzg_proofs (25% missing)   | 61.589 ms |   25-30% |
| recover_cells_and_kzg_proofs (12.5% missing) | 57.518 ms | …

Optimize PeerDAS
